<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="E4795_Tech" ignored="0" name="SettingTest" tests="4" failures="2" timestamp="14 Feb 2020 15:32:14 GMT" time="371.307" errors="0">
  <testcase name="changePAssword" time="97.285" classname="com.ExtramarksWebsite_TestCases.SettingTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	ChangePassword Fail">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	ChangePassword Fail
	at com.ExtramarksWebsite_TestCases.SettingTest.changePAssword(SettingTest.java:149)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- changePAssword -->
  <testcase name="editProfile" time="97.513" classname="com.ExtramarksWebsite_TestCases.SettingTest"/>
  <testcase name="settingSubscription" time="131.887" classname="com.ExtramarksWebsite_TestCases.SettingTest"/>
  <testcase name="redeemVoucher" time="29.141" classname="com.ExtramarksWebsite_TestCases.SettingTest"/>
</testsuite> <!-- SettingTest -->
