<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="StudentNotesTest"
           tests="6"
           failures="3"
           errors="0"
           skipped="0"
           time="2459.444">
    <properties></properties>

            <testcase
                name="viewLesson"
                time="266.338"
                classname="com.ExtramarksWebsite_TestCases.StudentNotesTest">

            <failure type="java.lang.AssertionError" message="The following asserts failed:
	Verifying View Lesson from notes functionality Actual Result :  Expected Result : ,XII,Sociology: Indian Society,Introducing Indian Society expected [true] but found [false]">
                <![CDATA[java.lang.AssertionError: The following asserts failed:
	Verifying View Lesson from notes functionality Actual Result :  Expected Result : ,XII,Sociology: Indian Society,Introducing Indian Society expected [true] but found [false]
                org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)com.ExtramarksWebsite_TestCases.StudentNotesTest.viewLesson(StudentNotesTest.java:385)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)org.testng.internal.Invoker.invokeMethod(Invoker.java:661)org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)java.lang.Thread.run(Thread.java:748)
]]>
            </failure>
    </testcase>
            <testcase
                name="addNotes"
                time="165.334"
                classname="com.ExtramarksWebsite_TestCases.StudentNotesTest">

            <failure type="java.lang.AssertionError" message="The following asserts failed:
	Verifying add notes functionality expected [AddNotes_PASS] but found [AddNotes_Records_Not_Display_on_Grid_FAIL]">
                <![CDATA[java.lang.AssertionError: The following asserts failed:
	Verifying add notes functionality expected [AddNotes_PASS] but found [AddNotes_Records_Not_Display_on_Grid_FAIL]
                org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)com.ExtramarksWebsite_TestCases.StudentNotesTest.addNotes(StudentNotesTest.java:136)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)org.testng.internal.Invoker.invokeMethod(Invoker.java:661)org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)java.lang.Thread.run(Thread.java:748)
]]>
            </failure>
    </testcase>
            <testcase
                name="editNotes"
                time="478.449"
                classname="com.ExtramarksWebsite_TestCases.StudentNotesTest">

            <failure type="java.lang.AssertionError" message="The following asserts failed:
	Verifying edit notes functionality expected [EditNotes_PASS] but found [EditNotes_Records_not_Displayed_on_Grid_FAIL]">
                <![CDATA[java.lang.AssertionError: The following asserts failed:
	Verifying edit notes functionality expected [EditNotes_PASS] but found [EditNotes_Records_not_Displayed_on_Grid_FAIL]
                org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)com.ExtramarksWebsite_TestCases.StudentNotesTest.editNotes(StudentNotesTest.java:175)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)org.testng.internal.Invoker.invokeMethod(Invoker.java:661)org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)java.lang.Thread.run(Thread.java:748)
]]>
            </failure>
    </testcase>


            <testcase
                name="verifysharedNotes"
                time="809.077"
                classname="com.ExtramarksWebsite_TestCases.StudentNotesTest">
            </testcase>
            <testcase
                name="deleteNotes"
                time="353.201"
                classname="com.ExtramarksWebsite_TestCases.StudentNotesTest">
            </testcase>
            <testcase
                name="shareNotes"
                time="387.045"
                classname="com.ExtramarksWebsite_TestCases.StudentNotesTest">
            </testcase>
</testsuite>
